enum IronFishInitStatus {
  ERROR,
  NOT_STARTED,
  INITIALIZING_SDK,
  INITIALIZING_NODE,
  DOWNLOAD_SNAPSHOT,
  CHECKING_FOR_MIGRATIONS,
  INITIALIZED,
  STARTING_NODE,
  STARTED,
}

export default IronFishInitStatus
